sonar.projectKey=RediSetHack_RediSetHack-V2
sonar.organization=redisethack
sonar.projectName=RediSetHack-V2
sonar.host.url=https://sonarcloud.io

# Source and Test scoping
sonar.sources=apps/api/src,apps/web/src,packages/db/src
sonar.tests=apps/api/test,apps/api/src
sonar.test.inclusions=apps/api/test/**/*.ts,apps/api/src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/LEGACY/**,**/graphify-out/**,**/*.config.*,**/*.d.ts

# Test coverage ingestion
sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info
