// Generated by pnpm generate:resource. Do not edit manually.

import { Module } from '@nestjs/common';

import { AuthModule } from './auth/auth.module.js';
import { CodelabModule } from './codelab/codelab.module.js';

@Module({ imports: [AuthModule, CodelabModule] })
export class FeaturesModule {}
