// Generated by pnpm generate:resource. Do not edit manually.

import { Module } from "@nestjs/common";

import { AuthModule } from "./auth/auth.module.js";
import { DailyEventModule } from "./daily-event/daily-event.module.js";
import { QuestModule } from "./quest/quest.module.js";

@Module({ imports: [AuthModule, DailyEventModule, QuestModule] })
export class FeaturesModule {}