import { Module } from "@nestjs/common";

import { CharacterRepository } from "../auth/domain/ports/character.repository.js";
import {
  BadgeDefinitionRepository,
  QuestRepository,
  RegionRepository,
  StageRepository,
  ZoneRepository,
} from "./domain/ports.js";
import {
  DrizzleBadgeDefinitionRepository,
  DrizzleQuestRepository,
  DrizzleRegionRepository,
  DrizzleStageRepository,
  DrizzleZoneRepository,
} from "./infrastructure/drizzle-repositories.js";
import {
  CreateBadgeDefinitionUseCase,
  CreateCharacterUseCase,
  CreateQuestUseCase,
  CreateRegionUseCase,
  CreateStageUseCase,
  CreateZoneUseCase,
  DeleteBadgeDefinitionUseCase,
  DeleteCharacterUseCase,
  DeleteQuestUseCase,
  DeleteRegionUseCase,
  DeleteStageUseCase,
  DeleteZoneUseCase,
  GetBadgeDefinitionUseCase,
  GetCharacterUseCase,
  GetQuestUseCase,
  GetRegionUseCase,
  GetStageUseCase,
  GetZoneUseCase,
  UpdateBadgeDefinitionUseCase,
  UpdateCharacterUseCase,
  UpdateQuestUseCase,
  UpdateRegionUseCase,
  UpdateStageUseCase,
  UpdateZoneUseCase,
} from "./application/use-cases.js";
import {
  CreateBadgeDefinitionController,
  CreateCharacterController,
  CreateQuestController,
  CreateRegionController,
  CreateStageController,
  CreateZoneController,
  DeleteBadgeDefinitionController,
  DeleteCharacterController,
  DeleteQuestController,
  DeleteRegionController,
  DeleteStageController,
  DeleteZoneController,
  GetBadgeDefinitionController,
  GetCharacterController,
  GetQuestController,
  GetRegionController,
  GetStageController,
  GetZoneController,
  UpdateBadgeDefinitionController,
  UpdateCharacterController,
  UpdateQuestController,
  UpdateRegionController,
  UpdateStageController,
  UpdateZoneController,
} from "./presentation/controllers.js";

@Module({
  controllers: [
    CreateRegionController,
    GetRegionController,
    UpdateRegionController,
    DeleteRegionController,
    CreateZoneController,
    GetZoneController,
    UpdateZoneController,
    DeleteZoneController,
    CreateStageController,
    GetStageController,
    UpdateStageController,
    DeleteStageController,
    CreateQuestController,
    GetQuestController,
    UpdateQuestController,
    DeleteQuestController,
    CreateBadgeDefinitionController,
    GetBadgeDefinitionController,
    UpdateBadgeDefinitionController,
    DeleteBadgeDefinitionController,
    CreateCharacterController,
    GetCharacterController,
    UpdateCharacterController,
    DeleteCharacterController,
  ],
  providers: [
    { provide: RegionRepository, useClass: DrizzleRegionRepository },
    { provide: ZoneRepository, useClass: DrizzleZoneRepository },
    { provide: StageRepository, useClass: DrizzleStageRepository },
    { provide: QuestRepository, useClass: DrizzleQuestRepository },
    { provide: BadgeDefinitionRepository, useClass: DrizzleBadgeDefinitionRepository },
    {
      provide: CreateRegionUseCase,
      useFactory: (repo: RegionRepository) => new CreateRegionUseCase(repo),
      inject: [RegionRepository],
    },
    {
      provide: GetRegionUseCase,
      useFactory: (repo: RegionRepository) => new GetRegionUseCase(repo),
      inject: [RegionRepository],
    },
    {
      provide: UpdateRegionUseCase,
      useFactory: (repo: RegionRepository) => new UpdateRegionUseCase(repo),
      inject: [RegionRepository],
    },
    {
      provide: DeleteRegionUseCase,
      useFactory: (repo: RegionRepository) => new DeleteRegionUseCase(repo),
      inject: [RegionRepository],
    },
    {
      provide: CreateZoneUseCase,
      useFactory: (repo: ZoneRepository, regions: RegionRepository) => new CreateZoneUseCase(repo, regions),
      inject: [ZoneRepository, RegionRepository],
    },
    {
      provide: GetZoneUseCase,
      useFactory: (repo: ZoneRepository) => new GetZoneUseCase(repo),
      inject: [ZoneRepository],
    },
    {
      provide: UpdateZoneUseCase,
      useFactory: (repo: ZoneRepository) => new UpdateZoneUseCase(repo),
      inject: [ZoneRepository],
    },
    {
      provide: DeleteZoneUseCase,
      useFactory: (repo: ZoneRepository) => new DeleteZoneUseCase(repo),
      inject: [ZoneRepository],
    },
    {
      provide: CreateStageUseCase,
      useFactory: (repo: StageRepository, zones: ZoneRepository) => new CreateStageUseCase(repo, zones),
      inject: [StageRepository, ZoneRepository],
    },
    {
      provide: GetStageUseCase,
      useFactory: (repo: StageRepository) => new GetStageUseCase(repo),
      inject: [StageRepository],
    },
    {
      provide: UpdateStageUseCase,
      useFactory: (repo: StageRepository) => new UpdateStageUseCase(repo),
      inject: [StageRepository],
    },
    {
      provide: DeleteStageUseCase,
      useFactory: (repo: StageRepository) => new DeleteStageUseCase(repo),
      inject: [StageRepository],
    },
    {
      provide: CreateQuestUseCase,
      useFactory: (repo: QuestRepository, stages: StageRepository) => new CreateQuestUseCase(repo, stages),
      inject: [QuestRepository, StageRepository],
    },
    {
      provide: GetQuestUseCase,
      useFactory: (repo: QuestRepository) => new GetQuestUseCase(repo),
      inject: [QuestRepository],
    },
    {
      provide: UpdateQuestUseCase,
      useFactory: (repo: QuestRepository) => new UpdateQuestUseCase(repo),
      inject: [QuestRepository],
    },
    {
      provide: DeleteQuestUseCase,
      useFactory: (repo: QuestRepository) => new DeleteQuestUseCase(repo),
      inject: [QuestRepository],
    },
    {
      provide: CreateBadgeDefinitionUseCase,
      useFactory: (repo: BadgeDefinitionRepository) => new CreateBadgeDefinitionUseCase(repo),
      inject: [BadgeDefinitionRepository],
    },
    {
      provide: GetBadgeDefinitionUseCase,
      useFactory: (repo: BadgeDefinitionRepository) => new GetBadgeDefinitionUseCase(repo),
      inject: [BadgeDefinitionRepository],
    },
    {
      provide: UpdateBadgeDefinitionUseCase,
      useFactory: (repo: BadgeDefinitionRepository) => new UpdateBadgeDefinitionUseCase(repo),
      inject: [BadgeDefinitionRepository],
    },
    {
      provide: DeleteBadgeDefinitionUseCase,
      useFactory: (repo: BadgeDefinitionRepository) => new DeleteBadgeDefinitionUseCase(repo),
      inject: [BadgeDefinitionRepository],
    },
    {
      provide: CreateCharacterUseCase,
      useFactory: (repo: CharacterRepository) => new CreateCharacterUseCase(repo),
      inject: [CharacterRepository],
    },
    {
      provide: GetCharacterUseCase,
      useFactory: (repo: CharacterRepository) => new GetCharacterUseCase(repo),
      inject: [CharacterRepository],
    },
    {
      provide: UpdateCharacterUseCase,
      useFactory: (repo: CharacterRepository) => new UpdateCharacterUseCase(repo),
      inject: [CharacterRepository],
    },
    {
      provide: DeleteCharacterUseCase,
      useFactory: (repo: CharacterRepository) => new DeleteCharacterUseCase(repo),
      inject: [CharacterRepository],
    },
  ],
})
export class ContentModule {}
