name: CI

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]
  push:
    branches: [develop, main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Workspace
        uses: ./.github/actions/setup-workspace

      - name: Lint
        run: pnpm turbo lint

      - name: Typecheck
        run: pnpm turbo check-types

      - name: Test
        run: pnpm turbo test

      - name: Build
        run: pnpm turbo build
